name: pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    brances: [main]
    types: [opened, synchronize]

jobs:
  linting-and-testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: action/checkout@v4
      - uses: action/setup-node@v4
        with:
          node-version: 20
      
      - name: install deps
        run: npm install-all

      - name: linting
        run: npm run lint

      - name: testing
        run: npm run test:back