name: pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  linting-and-testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: install deps
        run: npm run install-all

      - name: Check ESLint and cross-env permissions
        run: |
          chmod +x node_modules/.bin/eslint || true
          chmod +x node_modules/.bin/cross-env || true

      - name: linting
        run: npm run lint

      - name: testing
        run: npm run test:back
        env:
          URI_TEST: ${{secrets.URI_TEST}}